### ISSUE TITLE
Undefined symbol "__opws_fix_Weather" & Opcodes

### ISSUE THREAD

**Issue by ReshiramZekrom1** [boorzz/samp-opws-fix#3]
https://github.com/boorzz/samp-opws-fix/blob/2a2716a13c59041d14927cd77ef905a03806337d/opws_fix.inc#L109

Hey man, you forgot to create the "__opws_fix_Weather" variable. I would fix this issue myself but idk if this was omitted because not needed since it isn't used at all in the RPC edit.

Also, I was testing the script on different gamemodes and I noticed some critical opcodes in one of them. 

I think I found the reason which is due to the amount of vehicles in the spawn zone. Once I removed all the vehicles from there I didn't get the error again. This one was just a test so it's fine, but my fear is that this could lead to other crashes in the future. I'll just report this experience and I'll run other tests in the next days, expecially on the gamemode I want to use this. I'll tell you if I find some workarounds.

Been wondering just why the "Connected to" message is repeated three times and not just twice.

Thank you!

Chatlog:

```
[16:15:39] Connected to {B9C9BF}marineserverprova

[16:15:41] Connected to {B9C9BF}marineserverprova

[16:15:41] Warning(opcode 0x38B): Exception 0xC0000005 at 0x4C8F24

[16:15:41] Connected to {B9C9BF}marineserverprova

[16:15:41] Warning(s007): Exception 0xC0000005 at 0x4C8F24

[16:15:41] Warning(s007): Exception 0xC0000005 at 0x4C8F24

[16:15:41] Warning(s007): Exception 0xC0000005 at 0x4C8F24

[16:15:41] Warning(s007): Exception 0xC0000005 at 0x4C8F24

[16:15:42] Warning(s007): Exception 0xC0000005 at 0x4C8F24

[16:15:42] Warning(s007): Exception 0xC0000005 at 0x4C8F24

[16:15:42] Warning(s007): Exception 0xC0000005 at 0x4C8F24
```

**Comment by boorzz** [comment]
> You forgot to create the "__opws_fix_Weather" variable. I would fix this issue myself but idk if this was omitted because not needed since it isn't used at all in the RPC edit.

Ahh yeah, I forgot several things actually. I have fixed it in the latest version, thank you!

> I think I found the reason which is due to the amount of vehicles in the spawn zone. Once I removed all the vehicles from there I didn't get the error again

Hmm I couldn't reproduce the bug, I created a new branch called **models-fix** with a possible fix but I'm not sure if it works, test if the warning is still showing with that version please.

> Been wondering just why the "Connected to" message is repeated three times and not just twice.

That's because I send the RPC which initializes the most essential things (like the server name, **the server lagcomp**, etc) when the player calls OnPlayerSpawn for the first time. Unfortunately those messages show up when that RPC is sent and I can't do anything to hide them, sorry. :(

**Comment by ReshiramZekrom1** [comment]
Thank you for the support!

I've tested the models-fix branch but nothing seems different and I always get the same warnings as before which lead to crashes.

I've then tried to remove the OnPlayerSpawn hook and as well the TogglePlayerSpectating functions and I moved everything under OnPlayerConnect, then run another test and I didn't get any warnings whatsoever.

I'm sure you already tried OnPlayerConnect once and that you relied on OnPlayerSpawn because you cross problems of any sort, isn't it? Because, if this is not the case, I think using OPC could be a life saver imho since forcing the player to respawn isn't the best and this could lead to crashes as it happened to me.

I've created a pull request, with all the changes I made. I'm not that used to GitHub so I'm sorry if this seems odd to you, ahah

**Comment by boorzz** [comment]
> I'm sure you already tried OnPlayerConnect once and that you relied on OnPlayerSpawn because you crossed problems of some sort, isn't it? Because, if this is not the case, I think using OPC could be a life saver imho since forcing the player to respawn isn't the best and this could lead to crashes as it happened to me.

When I was writing this library I remember having problems with OPC, but I think it was something from the early versions when I was using YSF, I tried it again with Pawn.RakNet and it works! Thanks for reminding me of the OPC :)

> I've created a pull request, with all the changes I made. I'm not that used to GitHub so I'm sorry if this seems odd to you, ahah

Don't worry, it's perfect, there would only be one thing missing which is to send the InitGame RPC once again to change the lagcomp to lagshot, and as you said in the pull request, __opws_fix_PlayerFixCount is no longer necessary.

I merged your pull request and made a commit adding the missing rpc, thank you so much for the help! <3
